sudo: required
language: node_js
node_js:
- '4.1'
services:
- docker
env:
  global:
  - secure: c0pMDCWuDuV4Wx7BHewvPclkPoNZc8ocHv7jPXKawS4m2evQogMuO7pejNzZrZ4Of3hE1xG8dcfQ9M7RupYaLQ6SNmPpTPePPYuQZrnwOkqI3CizSPJa3QlDPOHphYZEjD/bQHi6Gq4TvRRjSLz60g9m/XBdnMpfm04v4o/bd31WMDx2zdXY6g04sz8D5zVSWJYuzJXL5r9J8NilnGHP4DU48gfNO7XF9SCbimv8wVbfquAhOYpYtryFoTvYbTy0HrQ+PB58c5UVsBdKRHq0Y/JhvmIFkZovBAFdKo0t8wKPyo2p18pY4Nf0i05JExg0iMV64/zTTO58D85wtpVdT0hGSiIELrH5mq5xkEG7xDJygTTTqxjFSCcFHatny/q9re4Qow8KvrsqBiAXv5PhknqvPuIevnGqoquWQHIvtx5mWqkU1hJR9IflDMamZkMLl2U9jPSuLz+02UtI0Yrq5YlIThQexRFRUWMYAWuQlGWr5B/LHlc1KHXqX9ggdcfDWDdFdPZUjfaYfFvghygcgbQGxHVuFr4FqYGf1Mf2eP30vL9HH6ZdACAWSYUHpTcUHsRg5DMaTJ/MFdnu9oYFpKqQFRvi43JvgofbBI7UbekfvUCfTqZfhZTc4JetCMK5ITJxMgkt4Cm5S+wUw2dcPVrgsdepZI0QonDcdWVvjPg=
  - secure: MY9CrP6O6HtzoDEL9AtZIQIvOkslFWWF8yrviDMkvMIVPJnw5g8T3GFN0OXxf6pNNZ9I3zJWih2tjKTkTibXUQRqQNr5cupjHGmqBRzk7vBVQ8DkqXIb2nCaUg75lbzpVfdPbQtM+0L8ldPUgQn9BAUdXWdfPa0gcKbb0QsLUxiGUTHIDLbgoyLF5ZNDAJSsYM8uSC0m5p/dt6P2sy7MsGHLAQmtCfYnYZ3kpDVsAhJc8jwMRyhG86mcYIf0um2t7oj1m9Qd8f14DYyXao/MG6aGwsbNU+29v5CMIxTSjCIYmc4KkaJjxFAGTSP6i4GYoXKdI+KJRJctvuEzo3lnO5Mzp7OQStUmgceadsHDYmC2YX6mGROEBofDiLpoe4sa08Rln/aHPcrb0jQMoSdgeR78RBUiHESZqBuocdRSg0OkbhHMUdUPakwKHMBKltkSygDIUr7cIXLZyfLmQ811uqDBaz0O9MYp1mZu0uqVOmWpgQ8IGygcC+jgl2flWyu4MnjxzC1ntZdfDfPUEEIxfZjU/LW/R4JYvBA1NSlYlun//vuFsSw5rXPEl7gqMvnErV/gMXQbbu4yGaG70d/Ym2cDj66GU+UR1UwtZrRpMThYCPbxrmgItGbxWIEwI5+1sPb+nuoq68lSYgo+xcwUU0Yi/u5bP5UQ585Z3gLutsU=
  - secure: MrcZpRbEPujvEBViUFxt1/N4Rso4jTwEnrQn4ZO3UiHrmAzUO2ObiybqfXSc5+kb6keDUshkoiYGuJEk+6pMQrlSFALchfyF49E4w+J9+bTCcXmGMjJDKmJU1p6D1qumUN97t29tkZ6z7A8p8W23wOINRCRSkHBa+Bcj7fN66KezPfGsGSCCBbt3lSAHlVI+U9NN6XIEyQ0tujeAbs53Zbh7px65TQxUwGlL3lCF7pD314zOMdyQKJkre+SFf86qQ8gJPsFaWReVzo8g0NcRKchr2VDhadwBGgKrDQGrumVJa6VgeJEFoncpGxTON61J4TiZz7YuYgP+FLae3yxOcZmX31hZWsOIPsQZ2jK3q2F9zp9b6j2Ac/uac1ivENIvMpftc0QVOMkQqNWl+qWQJO0J4Hy03pZm9lU3NqiEWVMjCq2TWm678pcMoundrgMVQ/fNcHY4qGJWzYKS+JoQ/RBQcQ/4LXnzbBE8Wbgs7Z7h5SuPYQEseulBtjewvkryr5CGE5V3P3vK3uuOOelVdRZUid8NHqyadknpk4puvyTV/vMtPy6V6BKWi5BULmAdXsWcGYH42a2tuSVWNsicdLhYxobrWzaIpICFWDRYVfdWdR3wKjO6LSf5BDIfIMmj20u9jGjsW69UgzfLJmWMd/3LXHll33YNncrUfiCQN6w=
before_install:
- composer install
- export REPO=bertrandxyz/pipeline
- docker build -f Dockerfile -t $REPO .
- docker-compose up -d
script: gulp
after_success:
- docker login -e "$DOCKER_EMAIL" -u "$DOCKER_USER" -p "$DOCKER_PASS"
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;  fi`
- docker tag -f $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
- docker push $REPO
