pipeline:
  container_name: pipeline
  image: pipeline
  restart: always
  ports:
    - "80:80"
  links:
    - db-pipeline

db-pipeline:
    container_name: db-pipeline
    image: mysql
    restart: always
    ports:
        - "3306:3306"
    volumes:
        - /var/lib/mysql
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=pipeline
        - MYSQL_USER=user
        - MYSQL_PASSWORD=pass

